<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_hargaItemCart</name>
   <tag></tag>
   <elementGuidId>8cd32e6d-5e66-4675-99f8-58195d31c2a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class='cart_list']/div[@class='cart_item']/descendant::a)[${index}]/following-sibling::div[@class='item_pricebar']/div[@class='inventory_item_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
